###
POST http://localhost:3000/login/
Content-Type: application/json
{
    "username": "christopher_phillips",
    "password": "christy@123"
}

###
GET http://localhost:3000/states/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc4MDQyfQ.e6n4C-4yAz5iGLXx_ql8D8uorz1hDaUCHUL4ZQnFj-E

###
GET http://localhost:3000/states/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc4MDQyfQ.e6n4C-4yAz5iGLXx_ql8D8uorz1hDaUCHUL4ZQnFj-E

###
POST http://localhost:3000/districts/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc4MDQyfQ.e6n4C-4yAz5iGLXx_ql8D8uorz1hDaUCHUL4ZQnFj-E
Content-Type: application/json
{
    "districtName": "Bagalkot",
    "stateId": 3,
    "cases": 2323,
    "cured": 2000,
    "active": 315,
    "deaths": 8
}

###
GET http://localhost:3000/districts/322/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc4MDQyfQ.e6n4C-4yAz5iGLXx_ql8D8uorz1hDaUCHUL4ZQnFj-E

###
DELETE http://localhost:3000/districts/8/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc5NjE4fQ.DVmNL1HR8mehR_3n4aIm5NFZgWC_BBAf253_ADX-vCk

###
PUT http://localhost:3000/districts/7/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc5NjE4fQ.DVmNL1HR8mehR_3n4aIm5NFZgWC_BBAf253_ADX-vCk
Content-Type: application/json
{
    "districtName": "Nadia",
    "stateId": 3,
    "cases": 9628,
    "cured": 6524,
    "active": 3000,
    "deaths": 104
}

###
GET http://localhost:3000/states/8/stats/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImNocmlzdG9waGVyX3BoaWxsaXBzIiwiaWF0IjoxNzUzNjc5NjE4fQ.DVmNL1HR8mehR_3n4aIm5NFZgWC_BBAf253_ADX-vCk


